/**
 * =================================================================
 * INDIGENOUS PROCUREMENT POLICY (IPP) CONTENT DATA
 * =================================================================
 *
 * Comprehensive data for IPP-related pages and components.
 * This is the single source of truth for all IPP statistics,
 * policy details, and educational content.
 *
 * Sources:
 * - NIAA: https://www.niaa.gov.au/indigenous-procurement-policy-ipp
 * - Department of Finance: https://www.finance.gov.au/government/procurement
 * - Supply Nation: https://supplynation.org.au
 */

// =================================================================
// IPP STATISTICS
// =================================================================

export const ippStats = {
  /** Total value of Indigenous contracts since 2015 */
  totalContractValue: "$12.9 billion",
  totalContractValueRaw: 12900000000,

  /** Total number of contracts awarded */
  totalContracts: "83,500+",
  totalContractsRaw: 83500,

  /** Number of Indigenous businesses receiving contracts */
  businessesAwarded: "4,600+",
  businessesAwardedRaw: 4600,

  /** FY2023-24 Indigenous supplier spend */
  annualSpend2024: "$5.83 billion",
  annualSpend2024Raw: 5830000000,

  /** Annual social value generated by Indigenous businesses */
  annualSocialValue: "$42.6 billion",
  annualSocialValueRaw: 42600000000,

  /** Social return multiplier per $1 spent */
  socialReturnMultiplier: 4.41,
  socialReturnMultiplierDisplay: "$4.41",

  /** Alternative social impact figure (Sleeping Giant Rises report) */
  socialImpactPerDollar: 3.66,
  socialImpactPerDollarDisplay: "$3.66",

  /** Indigenous businesses are X times more likely to employ Indigenous people */
  employmentMultiplier: 100,
  employmentMultiplierDisplay: "100x",

  /** Number of Supply Nation corporate members */
  supplyNationCorporateMembers: "850+",
  supplyNationCorporateMembersRaw: 850,

  /** Number of certified Indigenous businesses */
  certifiedBusinesses: "5,000+",
  certifiedBusinessesRaw: 5000,

  /** Number of organisations with RAPs */
  organisationsWithRAPs: "2,500+",
  organisationsWithRAPsRaw: 2500,
} as const;

// =================================================================
// POLICY THRESHOLDS
// =================================================================

export const ippThresholds = {
  /** Mandatory Set Aside threshold (GST inclusive) */
  msaMinimum: 80000,
  msaMinimumDisplay: "$80,000",
  msaMaximum: 200000,
  msaMaximumDisplay: "$200,000",
  msaRange: "$80,000 - $200,000",

  /** Mandatory Minimum Requirements threshold */
  mmrThreshold: 7500000,
  mmrThresholdDisplay: "$7.5 million",

  /** MMR Indigenous participation target */
  mmrParticipationTarget: 4, // percent
  mmrParticipationTargetDisplay: "4%",

  /** SME employee limit for Exemption 16 */
  smeEmployeeLimit: 200,

  /** Number of industry sectors covered by MMR */
  mmrIndustrySectors: 19,
} as const;

// =================================================================
// GOVERNMENT TARGETS (2024-2030)
// =================================================================

export const governmentTargets = [
  { year: "2024-25", target: 2.5, display: "2.5%" },
  { year: "2025-26", target: 3.0, display: "3.0%" },
  { year: "2026-27", target: 3.25, display: "3.25%" },
  { year: "2027-28", target: 3.5, display: "3.5%" },
  { year: "2028-29", target: 3.75, display: "3.75%" },
  { year: "2029-30", target: 4.0, display: "4.0%" },
] as const;

// =================================================================
// STATE GOVERNMENT POLICIES
// =================================================================

export const statePolicies = [
  {
    state: "Commonwealth",
    policyName: "Indigenous Procurement Policy (IPP)",
    target: "3% (2025-26)",
    keyThreshold: "$80K-$200K Mandatory Set Aside",
    url: "https://www.niaa.gov.au/indigenous-procurement-policy-ipp",
  },
  {
    state: "Queensland",
    policyName: "Queensland Indigenous Procurement Policy (QIPP)",
    target: "3% of addressable spend",
    keyThreshold: "$440M awarded in FY21-22",
    url: "https://www.dsdsatsip.qld.gov.au/our-work/aboriginal-torres-strait-islander-partnerships/business-economic-development/queensland-indigenous-procurement-policy",
  },
  {
    state: "New South Wales",
    policyName: "Aboriginal Procurement Policy",
    target: "1% spend, 3% of contracts",
    keyThreshold: "First consideration to $250K",
    url: "https://www.info.buy.nsw.gov.au/policy-library/policies/aboriginal-procurement-policy",
  },
  {
    state: "Victoria",
    policyName: "Social Procurement Framework",
    target: "1% of SME procurement",
    keyThreshold: "$20M+ requires Indigenous targets",
    url: "https://www.buyingfor.vic.gov.au/social-procurement-victorian-government-approach",
  },
  {
    state: "Western Australia",
    policyName: "Aboriginal Procurement Policy",
    target: "Varies by agency",
    keyThreshold: "Priority consideration for Indigenous businesses",
    url: "https://www.wa.gov.au/government/document-collections/aboriginal-procurement-policy",
  },
] as const;

// =================================================================
// KEY POLICY MECHANISMS
// =================================================================

export const policyMechanisms = {
  mandatorySetAside: {
    name: "Mandatory Set Aside (MSA)",
    shortDescription: "Indigenous businesses get first opportunity for contracts $80K-$200K",
    fullDescription: `For any Commonwealth procurement between $80,000 and $200,000 (GST inclusive) delivered wholly in Australia, government buyers MUST:

1. Search Supply Nation's Indigenous Business Directory first
2. Give Indigenous businesses the opportunity to quote
3. Award the contract if the Indigenous business demonstrates "value for money"
4. Only go to open market if no Indigenous supplier can deliver

This is not optional - it's mandatory under the Commonwealth Procurement Rules.`,
    applies: "Contracts $80,000 - $200,000 (GST inclusive)",
    benefit: "Skip competitive tender - direct approach allowed",
  },
  exemption16: {
    name: "Exemption 16",
    shortDescription: "Direct procurement from Indigenous SMEs at ANY contract value",
    fullDescription: `Exemption 16 of the Commonwealth Procurement Rules enables government buyers to purchase directly from Indigenous small and medium enterprises (SMEs) for contracts of ANY size and value - without going to open tender.

Requirements:
- Business must be an SME (under 200 employees)
- Simple quote process (not full tender)
- Value for money must be demonstrated
- Appropriate sign-off authority based on value

This means government can buy directly from Indigenous suppliers even for contracts worth millions.`,
    applies: "Any contract value (SME suppliers only)",
    benefit: "Bypass tender process entirely",
  },
  mmr: {
    name: "Mandatory Minimum Requirements (MMR)",
    shortDescription: "Large contracts must include Indigenous participation",
    fullDescription: `For contracts valued at $7.5 million or more in 19 specified industry sectors, contractors must achieve:

- 4% of the workforce must be Indigenous Australians, OR
- 4% of contract value must be subcontracted to Indigenous businesses, OR
- A combination of both approaches

This means large contractors NEED Indigenous suppliers in their supply chain to win government bids. They're actively seeking verified Indigenous businesses to meet these requirements.`,
    applies: "Contracts $7.5M+ in specified sectors",
    benefit: "Tier 1 contractors need you in their supply chain",
  },
} as const;

// =================================================================
// VALUE FOR MONEY FACTORS
// =================================================================

export const valueForMoneyFactors = [
  {
    factor: "Quality and fitness for purpose",
    description: "The product or service meets the buyer's actual needs",
  },
  {
    factor: "Supplier capability and experience",
    description: "Demonstrated track record and technical competence",
  },
  {
    factor: "Risk mitigation",
    description: "Reduced procurement risk through proven delivery",
  },
  {
    factor: "Social and economic benefits",
    description: "Including Indigenous employment and ownership - this is explicitly allowed",
  },
  {
    factor: "Ethical conduct",
    description: "Added November 2025 - business practices and integrity",
  },
] as const;

// =================================================================
// BUYER BENEFITS
// =================================================================

export const governmentBuyerBenefits = [
  {
    title: "Mandatory Compliance Met",
    description: "Must search Supply Nation first for $80K-$200K contracts",
    icon: "CheckCircle",
  },
  {
    title: "Portfolio Targets Achieved",
    description: "Help your department meet Indigenous procurement KPIs",
    icon: "Target",
  },
  {
    title: "Direct Approach (Exemption 16)",
    description: "Buy directly at any value without open tender",
    icon: "Zap",
  },
  {
    title: "Simplified Process",
    description: "Skip lengthy tender processes with direct engagement",
    icon: "Clock",
  },
  {
    title: "Audit Protection",
    description: "Clear documentation of Indigenous procurement compliance",
    icon: "Shield",
  },
  {
    title: "Same Quality Products",
    description: "HP enterprise printers - identical to any other dealer",
    icon: "Award",
  },
] as const;

export const corporateBuyerBenefits = [
  {
    title: "RAP Compliance",
    description: "Meet your Reconciliation Action Plan procurement targets",
    icon: "FileCheck",
  },
  {
    title: "ESG Reporting",
    description: "Tangible social impact metrics for sustainability reports",
    icon: "BarChart3",
  },
  {
    title: "$4.41 Social Multiplier",
    description: "Every dollar generates 4x the social value",
    icon: "TrendingUp",
  },
  {
    title: "Tender Advantage",
    description: "Better scores on government contracts you bid for",
    icon: "Trophy",
  },
  {
    title: "Brand Reputation",
    description: "Demonstrate genuine commitment to reconciliation",
    icon: "Heart",
  },
  {
    title: "Stakeholder Expectations",
    description: "Meet shareholder, employee, and customer expectations",
    icon: "Users",
  },
] as const;

export const tier1ContractorBenefits = [
  {
    title: "4% Supply Chain Target",
    description: "We count toward your Indigenous supplier spend requirements",
    icon: "Package",
  },
  {
    title: "Competitive Tender Advantage",
    description: "Strong Indigenous Participation Plan scores higher",
    icon: "Award",
  },
  {
    title: "Simplified Compliance",
    description: "One verified supplier for all print/document needs",
    icon: "CheckSquare",
  },
  {
    title: "Ongoing Relationship",
    description: "Managed print services = recurring Indigenous spend",
    icon: "RefreshCcw",
  },
] as const;

// =================================================================
// FAQ CONTENT
// =================================================================

export const ippFAQs = [
  {
    question: "What is the Indigenous Procurement Policy (IPP)?",
    answer: `The IPP is an Australian Government policy that aims to increase opportunities for Indigenous businesses to win government contracts. It includes mandatory requirements for government buyers to consider Indigenous suppliers first for certain contracts, and targets for overall Indigenous procurement spending.`,
  },
  {
    question: "What is the Mandatory Set Aside?",
    answer: `For contracts between $80,000 and $200,000 (GST inclusive), government buyers must give Indigenous businesses the first opportunity to demonstrate value for money before going to the open market. This means as an Indigenous supplier, we get priority consideration for contracts in this range.`,
  },
  {
    question: "What is Exemption 16?",
    answer: `Exemption 16 allows government buyers to purchase directly from Indigenous SMEs (under 200 employees) for contracts of any value - without going through a full tender process. Value for money must still be demonstrated, but this can be done through a simple quote process.`,
  },
  {
    question: "Does buying from an Indigenous supplier cost more?",
    answer: `No. We offer competitive pricing on the same HP enterprise products available from any dealer. The difference is that your purchase generates additional social value - Supply Nation research shows $4.41 of social return for every $1 spent with Indigenous businesses.`,
  },
  {
    question: "What does 'value for money' mean for Indigenous procurement?",
    answer: `Value for money is NOT just about the lowest price. Government procurement rules explicitly allow consideration of social and economic benefits, including Indigenous employment and ownership. Quality, capability, risk mitigation, and ethical conduct are all valid factors.`,
  },
  {
    question: "How does this help with RAP commitments?",
    answer: `Many organisations have Reconciliation Action Plans (RAPs) with specific Indigenous procurement targets. Purchasing from us counts directly toward those targets, providing measurable progress on your RAP commitments.`,
  },
  {
    question: "Are you Supply Nation certified?",
    answer: `Yes. We are Supply Nation certified, which means our Indigenous ownership has been independently verified. This certification is recognised by government and corporate buyers as the standard for Indigenous business verification.`,
  },
  {
    question: "How does this benefit Tier 1 contractors?",
    answer: `For contracts over $7.5 million, contractors must meet Mandatory Minimum Requirements (MMR) - typically 4% Indigenous workforce or 4% subcontracted to Indigenous businesses. Using us as your print supplier contributes to that 4% target.`,
  },
] as const;

// =================================================================
// SOCIAL IMPACT CALCULATOR DATA
// =================================================================

export const socialImpactData = {
  multiplier: 4.41,
  impactCategories: [
    { category: "Employment Creation", weight: 0.25 },
    { category: "Community Investment", weight: 0.20 },
    { category: "Skills Development", weight: 0.20 },
    { category: "Cultural Preservation", weight: 0.15 },
    { category: "Economic Independence", weight: 0.20 },
  ],
  reportMetrics: [
    "Direct Indigenous employment supported",
    "Social return on investment (SROI)",
    "Contribution to Closing the Gap targets",
    "Community benefit distribution",
    "Indigenous business sector growth",
  ],
} as const;

// =================================================================
// IPP COMPLIANCE CHECKER DATA
// =================================================================

export const complianceCheckerOptions = {
  contractValues: [
    { label: "Under $80,000", value: "under80k", msa: false, mmr: false },
    { label: "$80,000 - $200,000", value: "80k-200k", msa: true, mmr: false },
    { label: "$200,000 - $7.5 million", value: "200k-7.5m", msa: false, mmr: false },
    { label: "Over $7.5 million", value: "over7.5m", msa: false, mmr: true },
  ],
  deliveryLocations: [
    { label: "Metropolitan Australia", value: "metro", remoteBonus: false },
    { label: "Regional Australia", value: "regional", remoteBonus: false },
    { label: "Remote Australia", value: "remote", remoteBonus: true },
  ],
  organisationTypes: [
    { label: "Commonwealth Government", value: "commonwealth" },
    { label: "State Government", value: "state" },
    { label: "Local Government", value: "local" },
    { label: "Corporate (with RAP)", value: "corporate-rap" },
    { label: "Corporate (without RAP)", value: "corporate-no-rap" },
    { label: "Tier 1 Contractor", value: "tier1-contractor" },
  ],
} as const;

// =================================================================
// PAGE METADATA
// =================================================================

export const ippPageMeta = {
  whyIndigenous: {
    title: "Why Choose an Indigenous Supplier | Dreaming Print Solutions",
    description: "Same enterprise quality. Greater social impact. Learn how purchasing from an Indigenous-owned HP dealer generates $4.41 of social value for every $1 spent.",
    keywords: [
      "indigenous supplier benefits",
      "why choose indigenous business",
      "indigenous procurement advantages",
      "social return on investment indigenous",
      "supply nation benefits",
    ],
  },
  governmentProcurement: {
    title: "Government Procurement | IPP Compliance Made Simple | Dreaming Print Solutions",
    description: "Simplify IPP compliance with enterprise print solutions from an Indigenous supplier. Mandatory Set Aside, Exemption 16, and MMR requirements explained.",
    keywords: [
      "government procurement indigenous",
      "IPP compliance",
      "mandatory set aside",
      "exemption 16 indigenous",
      "indigenous procurement policy",
    ],
  },
  corporateProcurement: {
    title: "Corporate Procurement | Meet Your RAP Targets | Dreaming Print Solutions",
    description: "Meet your Reconciliation Action Plan targets with enterprise-grade print solutions. Tangible social impact for ESG reporting from a Supply Nation certified supplier.",
    keywords: [
      "RAP procurement targets",
      "reconciliation action plan suppliers",
      "indigenous supplier corporate",
      "ESG indigenous procurement",
      "supply nation supplier",
    ],
  },
  ippGuide: {
    title: "Indigenous Procurement Policy (IPP) Complete Guide 2025 | Dreaming Print Solutions",
    description: "Everything you need to know about the Indigenous Procurement Policy. MSA, Exemption 16, MMR explained. State-by-state policies. Value for money guidance.",
    keywords: [
      "indigenous procurement policy guide",
      "IPP explained",
      "mandatory set aside guide",
      "indigenous business procurement",
      "government indigenous procurement",
    ],
  },
} as const;

// =================================================================
// CALL TO ACTION CONTENT
// =================================================================

export const ctaContent = {
  government: {
    headline: "Simplify Your IPP Compliance",
    subheadline: "Enterprise print solutions from an Indigenous supplier",
    primaryCTA: "Get a Quote",
    secondaryCTA: "Learn About IPP",
  },
  corporate: {
    headline: "Meet Your RAP Targets",
    subheadline: "Same HP quality. Greater social impact.",
    primaryCTA: "Calculate Your Impact",
    secondaryCTA: "See How It Works",
  },
  tier1: {
    headline: "Strengthen Your Indigenous Participation Plan",
    subheadline: "Verified Indigenous supplier for your supply chain",
    primaryCTA: "Partner With Us",
    secondaryCTA: "View Our Capabilities",
  },
} as const;

// =================================================================
// TYPE EXPORTS
// =================================================================

export type IPPStats = typeof ippStats;
export type IPPThresholds = typeof ippThresholds;
export type GovernmentTarget = (typeof governmentTargets)[number];
export type StatePolicy = (typeof statePolicies)[number];
export type PolicyMechanism = (typeof policyMechanisms)[keyof typeof policyMechanisms];
export type BuyerBenefit = (typeof governmentBuyerBenefits)[number];
export type IPPFAQ = (typeof ippFAQs)[number];
